libsemanage: mark semanage_array2plist() handle argument as unused
clang reports:

semanageswig_wrap.c:3596:22: error: unused parameter 'handle' [-Werror,-Wunused-parameter]
                semanage_handle_t* handle,
                                   ^